### ISSUE TITLE
VPM用のjsonの内容に不備がある。

### ISSUE THREAD

**Issue by mo4ca** [Tsukina-7mochi/glitch-shader#9]
package.jsonの内容に不備があり、VCCでinvalidになってしまうようです。
素人なので詳細までは確認していませんが、packageのキーがなかったりしているように見えます。

VPMで扱えたら大変助かりますので、ご確認いただけるとありがたいです。

**Comment by Tsukina-7mochi** [comment]
おそらく VPM のパッケージではなくレポジトリとして読み込んでいるようです (レポジトリはパッケージを集めたものです)。
現在レポジトリは作成していないため、パッケージとして読み込んでもらうとよいと思われます。

**Comment by tetra-dev** [comment]
ありがとうございます。
